version: '3.8'

services:
  sai-crud:
    build:
      context: .
      dockerfile: ${DOCKERFILE}
    container_name: sai-crud
    env_file:
      - .env
    ports:
      - "${SERVER_EXTERNAL_PORT}:${SERVER_PORT}"
    restart: unless-stopped
    networks:
      - sai-network
    volumes:
      - ./config.template.yml:/app/config.template.yml

networks:
  sai-network:
    name: sai-network
    driver: bridge
